import './globals.css'
import Navbar from '@/components/Navbar'
import { WalletAuthWrapper } from "../contexts/WalletAuth";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <WalletAuthWrapper>
        <body>
          <Navbar />
          {children}
        </body>
      </WalletAuthWrapper>
    </html>
  )
}
